### ISSUE TITLE
web xml rundeck version logic

### ISSUE THREAD

**Issue by atheiman** [sous-chefs/rundeck#134]
https://github.com/Webtrends/rundeck/commit/bf808ce99a1343ec5b2ca86d9bd98804a70bbaad prevents rundeck 2.7.0

**Comment by atheiman** [comment]
I think this can be solved by reading the version into rubygems version parsing

https://ruby-doc.org/stdlib-2.1.0/libdoc/rubygems/rdoc/Gem/Requirement.html

**Comment by nilroy** [comment]
@atheiman https://github.com/Webtrends/rundeck/pull/153 contains the implementation you mentioned

**Comment by gsreynolds** [comment]
Closing this issue as was resolved in #153 and there is now conditional logic on rundeck version in the relevant templates
