### ISSUE TITLE
Rundeck app user does not need sudo permissions

### ISSUE THREAD

**Issue by atheiman** [sous-chefs/rundeck#145]
Seems like the rundeck user does not need sudo permissions, but it is given permission to run all commands with sudo no password.

https://github.com/Webtrends/rundeck/blob/8a806f4024ff13662ac38a26330f3fe9afddb47b/recipes/node_unix.rb#L61-L64

**Comment by pcross616** [comment]
If the rundeck user does not have sudo commands in the RD job cannot execute functions like restarting a service or other privileged commands.  Which is very common when a user only has limited access to job execution.

**Comment by atheiman** [comment]
Im not sure why rundeck jobs need to restart services on the rundeck node, but if this is a requirement for consumers I think they should add sudo permissions as needed with something like the `sudo` cookbook: https://github.com/chef-cookbooks/sudo

I think the permission model should be giving `rundeck` user as little as it could need, and consumers of this cookbook can give the user more permissions as they require.

**Comment by nilroy** [comment]
If you absolutely don't want rundeck sudo then control using an attribute like node['rundeck']['user']['allow_sudo'] . Keep the default attribute to true.
