### ISSUE TITLE
Travis build is broken

### ISSUE THREAD

**Issue by nilroy** [sous-chefs/rundeck#157]
The Travis build is broken for quite some time now. The current master also does not pass the tests. Especially its the centOS. I have tried multiple things but it never worked. The tests are passing if I use my local machine (Mac OSX) by running ./.travish.sh script.

**Comment by edwlarkey** [comment]
It looks like master built just fine the last time it was ran. 
https://travis-ci.org/Webtrends/rundeck/branches

Is there a more recent test of master on travis that you could link to?

**Comment by edwlarkey** [comment]
I think I found the one you are referring to here https://travis-ci.org/Webtrends/rundeck/builds/215537188

Test from first commit to this PR https://github.com/Webtrends/rundeck/pull/155

**Comment by nilroy** [comment]
@edwlarkey The builds were running fine. But last week it just broke without any change that could affect it. If we run the build locally its passing. I ran the .travis.sh locally and the builds passes.

**Comment by ev0ldave** [comment]
builds are green!
