### ISSUE TITLE
Cookbook won't connect to the rundeck server due to outdated web.xml

### ISSUE THREAD

**Issue by voodoodror** [sous-chefs/rundeck#169]
### Cookbook version
3.2.1

### Chef-client version
12.17.44

### Rundeck version
rundeck-2.8.4-1.33.GA

### Platform Details
macOS Sierra 10.12.5 /w Vagrant Driver

### Scenario:
Installing rundeck cookbook.

### Steps to Reproduce:
Just run the cookbook OOTB /w the Rundeck version above.

### Expected Result:
The cookbook should proceed to the next steps after having successful connection to the Rundeck server. 

### Actual Result:
The cookbook gets stuck on connecting to Rundeck stage. It reaches timeout after a certain time.

### How I solved the issue:
Had to make a few changes in web.xml. These changes were takes from the Official Rundeck RPM (while preserving all the cookbook-template related sections).

**Comment by bpcook61** [comment]
I believe https://github.com/sous-chefs/rundeck/pull/164 will address this issue.

**Comment by ev0ldave** [comment]
@voodoodror can you test this with cookbook 4.1.0?

**Comment by acqant** [comment]
I'm suspecting the same, will test soon.

**Comment by acqant** [comment]
nah, #164 didn't fix it. 
Replaced web.xml with stock file from bpkg and rundeck starts up

**Comment by bpcook61** [comment]
Maintaining the web.xml as a Chef template is a real pain since they keep changing the packaged web.xml.

**Comment by gsreynolds** [comment]
Have installed and am running 2.9.x using master with the version attribute changes in #178 in production, plus local tests/local CI and [Travis for that PR](https://travis-ci.org/sous-chefs/rundeck/builds/268568532), not come across Rundeck failing to start? Might be something else at play here?

Is it only 2.9.x you are seeing the issue with as you seem to suggest in #164?

**Comment by acqant** [comment]
I was going to try master but I thought 4.1.1 had the fix we needed....brb...

**Comment by gsreynolds** [comment]
Well 4.1.1 == master just now, so it should 😄

**Comment by acqant** [comment]
@gsreynolds Huh?  Version 4.1.1 was done 28 days ago do someone just merge and push something???

Should I point metadata at master or leave it at 4.1.1 ( latest ) and try again?

**Comment by gsreynolds** [comment]
Sorry, I meant, the current version 4.1.1 and the master branch are [equivalent currently](https://github.com/sous-chefs/rundeck/commits/master) so either should work.

My experience in my is that #164 did fix it and I'm running 4.1.1/master with the version attributes overridden in a role to the values in #178 to install 2.9.3 and everything works as expected - I've not come across rundeck failing to start because of the web.xml template.

**Comment by acqant** [comment]
Using the debian package the rundeck_version ends up getting passed to the web.xml template as 1 and not 2.9.3

* log[2.9.3, 1, GA.deb] action write[2017-08-30T18:46:16+00:00] INFO: Processing log[2.9.3, 1, GA.deb] action write (cb-rundeck::default line 22)
       [2017-08-30T18:46:16+00:00] INFO: ["2.9.3", "1", "GA.deb"]
       
         
         * log[1] action write[2017-08-30T18:46:16+00:00] INFO: Processing log[1] action write (cb-rundeck::default line 23)
       [2017-08-30T18:46:16+00:00] INFO: 1

**Comment by acqant** [comment]
ahhh, our bad, someone set didn't use the full name 'rundeck-2.x.z-GA'

I'm on my way to getting this to work! Thanks.

**Comment by acqant** [comment]
So close, now after login I get an extra hostname in the redirect
* ruby_block[connect rundeck api client] action run[2017-08-31T19:40:32+00:00] WARN: 404       POST    http://alphac-bvlt-r1nrdeck/alphac-bvlt-r1nrdeck/menu/home BODY:

Not sure if it's rundeck server config, or cookbook setting... any ideas anyone?

**Comment by gsreynolds** [comment]
https://github.com/sous-chefs/rundeck/blob/01b5e6dba759baaf8e519ff746b05984c8b63608/recipes/_connect_rundeck_api_client.rb#L15

Check your values of `node['rundeck']['grails_server_url']` and `node['rundeck']['webcontext']`. At a guess I'd suggest webcontext has been changed from the default of `/`
