### ISSUE TITLE
Repo size is 172MB

### ISSUE THREAD

**Issue by gsreynolds** [sous-chefs/rundeck#171]
Rundeck repo is 172MB with ~9500 commits. I'm guessing it's the history from prior to the split from the monolithic cookbook repo and/or the binary files.

```
$ curl --silent https://api.github.com/repos/sous-chefs/rundeck |  jq '.size / 1024'
172.017578125
$ curl --silent https://api.github.com/repos/sous-chefs/apache2 |  jq '.size / 1024'
1.6142578125
```

Related: #38, #37 
@damacus

**Comment by ev0ldave** [comment]
we can run BFG again and pull out the winrm jar that is included in the files section.

**Comment by ev0ldave** [comment]
Binaries removed and cookbook_file calls replaced with remote_file.  Repo size is down to 25M.
