### ISSUE TITLE
can we get 4.1.0 released

### ISSUE THREAD

**Issue by atheiman** [sous-chefs/rundeck#172]
https://supermarket.chef.io/cookbooks/rundeck

**Comment by ev0ldave** [comment]
👍

**Comment by atheiman** [comment]
lol why was this closed with a 👍 ? i dont see it in supermarket yet. 

do the magical sous-chefs have an established way of deploying to supermarket via travis?

**Comment by ev0ldave** [comment]
Trigger happy, pcrossley is uploading the cookbook and transferring supermarket control from webtrends to sous-chefs

**Comment by atheiman** [comment]
ok, if i get access back to this repo id be happy to help out too

**Comment by ev0ldave** [comment]
http://sous-chefs.org/becoming-a-member/

**Comment by damacus** [comment]
Hey @atheiman, 

Also http://community-slack.chef.io/ #sous-chefs for where the community usually hangs out.
