### ISSUE TITLE
Write access to this repo

### ISSUE THREAD

**Issue by nilroy** [sous-chefs/rundeck#180]
Hi,

I would like to be a contributor to this repo. Could any one of the maintainers grant me access?

@pcross616 @ev0ldave 

Thanks & Regards
Nilanjan

**Comment by ev0ldave** [comment]
@nilroy we handed off management of this cookbook to sous-chefs because we could not give it the time that was needed to keep this up to date.  If you would like to become a maintainer please join sous-chefs and add yourself.
http://sous-chefs.org/becoming-a-member/

**Comment by PowerSchill** [comment]
Closing this issue as instructions for contributing were presented.
