### ISSUE TITLE
403 in RundeckApiClient with SSL when grails.serverURL is http

### ISSUE THREAD

**Issue by jwilf** [sous-chefs/rundeck#184]
### Cookbook version
4.2.0

### Chef-client version
Chef: 12.21.14

### Platform Details
CentOS release 6.9 (Final) on AWS

### Scenario:
Trying to configure rundeck with SSL handled by Apache2

### Steps to Reproduce:
default['rundeck']['use_inbuilt_ssl'] = false
default['rundeck']['use_ssl'] = true

Execute chef-client

### Expected Result:
chef-client completes and configures Rundeck, including adding Project from data bag.

### Actual Result:
403 Forbidden when adding the project using the API client (see attached)

The problem occurs when the grails.ServerURL is set to http, when the site is configured to use SSL. This happens because use_inbuilt_ssl is set to false, as I am using SSL offloading.

When I override default['rundeck']['grails_server_url'] to set the URL to https, the problem is resolved. Tracking this down cost me most of my day.

Thanks

[rundeck_failure.txt](https://github.com/sous-chefs/rundeck/files/1359553/rundeck_failure.txt)

**Comment by PowerSchill** [comment]
This ticket is no longer valid with the current release of the Rundeck cookbook which uses the Rundeck CLI.
