### ISSUE TITLE
Rundeck 3.x support

### ISSUE THREAD

**Issue by nilroy** [sous-chefs/rundeck#189]
When are we going to see rundeck 3.x support? The rundeck 3.x binaries has a different naming convention which is not backwards compatible.

**Comment by damacus** [comment]
Hi there! 

We would happily accept a pull request to resolve this issue. If you need help or guidance on submitting, please don't hesitate to ask! 

If you need help, or just wish to talk through issue please [join the Chef Community Slack](http://community-slack.chef.io/) and look for the #sous-chefs channel. 

Thanks,
Sous-Chefs

**Comment by ev0ldave** [comment]
I'm installing 3.x currently and getting the proper profile, rundeck-config, and jaas configuration changes up to date.  I will have a PR for these changes in the next day or two.  We are also planning a major rewrite to simplify this cookbook if you'd like to throw into the ring on it.

**Comment by nilroy** [comment]
@josephholsten Sorry I will not be able to create a PR at this moment. But if @ev0ldave is already working on this I would be more than happy
