### ISSUE TITLE
Please provide an example of using hash for admin policy 

### ISSUE THREAD

**Issue by gangadhar01a** [sous-chefs/rundeck#236]
Hi,

It will be nice if you can provide few examples of how a user can use the hash inside the recipe (server_install). I have been trying to set admin policy using, and provided the hash value as per the documentation, which is throwing an error 

"NoMethodError
    -------------
    undefined method `each' for "adminpolocy":String"

I request to update the documentation with some examples.

Thank you!

**Comment by PowerSchill** [comment]
I have an example in the unit tests. Look at https://github.com/sous-chefs/rundeck/blob/master/test/cookbooks/test/attributes/default.rb#L1 for an example.

**Comment by gangadhar01a** [comment]
Thank you. 
It worked.
