### ISSUE TITLE
"rundeck-config deprecation" changes are not reflecting 

### ISSUE THREAD

**Issue by gangadhar01a** [sous-chefs/rundeck#247]
hi @PowerSchill ,
I am using rundeck 5.0.2 cookbook, the changes which you have done in below PR not reflecting. I have to manually update the changes on machine and then I am able to install rundeck. Am I missing anything?

https://github.com/sous-chefs/rundeck/pull/234/files

**Comment by PowerSchill** [comment]
That is because those changes have not been pushed to the supermarket. You can either build from master or if you want I can generate a new release and push to the supermarket.

**Comment by gangadhar01a** [comment]
Having changes is supermarket definitely helps.

**Comment by PowerSchill** [comment]
Let me get a few of these cleanup issues closed and I can work on getting a release.

**Comment by gangadhar01a** [comment]
Thank you @PowerSchill
