### ISSUE TITLE
How I can avoid "test connection to the authentication endpoint"

### ISSUE THREAD

**Issue by gangadhar01a** [sous-chefs/rundeck#249]
Hi,

I am receiving a following open ssl error. However, the rundeck service is up and running and I am able to access it on port 4443. 

Is there a way to dodge/fix this check ?

"================================================================================
      Error executing action `run` on resource 'ruby_block[wait for rundeckd startup]'
      ================================================================================
      
      OpenSSL::SSL::SSLError
      ----------------------
      SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol
      
      Cookbook Trace:
      ---------------
      /home/chef-repo/.chef/local-mode-cache/cache/cookbooks/rundeck/resources/server_install.rb:351:in `block (3 levels) in class_from_file'
      
      Resource Declaration:
      ---------------------
      # In /home/chef-repo/.chef/local-mode-cache/cache/cookbooks/rundeck/resources/server_install.rb
      
      343:   ruby_block 'wait for rundeckd startup' do
      344:     action :nothing
      345:     block do
      346:       # test connection to the authentication endpoint
      347:       require 'uri'
      348:       require 'net/http'
      349:       uri = URI("#{new_resource.grails_server_url}:#{new_resource.grails_port}")
      350:       uri.path = ::File.join(new_resource.webcontext, '/j_security_check')
      351:       res = Net::HTTP.get_response(uri)
      352:       unless (200..399).cover?(res.code.to_i)
      353:         Chef::Log.warn { "#{res.uri} not responding healthy. #{res.code}" }
      354:         Chef::Log.debug { res.body }
      355:         raise
      356:       end
      357:       Chef::Log.info { 'wait a little longer for Rundeck startup' }
      358:       sleep new_resource.extra_wait
      359:     end
      360:     retries new_resource.retries
      
      Compiled Resource:
      ------------------
      # Declared in /home/chef-repo/.chef/local-mode-cache/cache/cookbooks/rundeck/resources/server_install.rb:343:in `block in class_from_file'
      
      ruby_block("wait for rundeckd startup") do
        action [:nothing]
        default_guard_interpreter :default
        declared_type :ruby_block
        cookbook_name "ganga"
        block #<Proc:0x0000000004dea540@/home/chef-repo/.chef/local-mode-cache/cache/cookbooks/rundeck/resources/server_install.rb:345>
        retries 60
        retry_delay 5
      end
"

**Comment by gangadhar01a** [comment]
I have updated the grails url to "https://localhost" and port to "4443" which is open for the network. 
Now I am getting an error related to certificate 

      ================================================================================
      _Error executing action `run` on resource 'ruby_block[wait for rundeckd startup]'
      ================================================================================
      
      OpenSSL::SSL::SSLError
      ----------------------
      SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate)
      
      Cookbook Trace:
      ---------------
      /home/chef-repo/.chef/local-mode-cache/cache/cookbooks/rundeck/resources/server_install.rb:351:in `block (3 levels) in class_from_file'_

**Comment by gangadhar01a** [comment]
Issue has been fixed by updating the port to 80 and url to http://localhost.

**Comment by gangadhar01a** [comment]
I am re-opening this ticket because of the following reason.
 
Rundeck went through start up script when I have provided the grailsURL : http://localhost and port 80 but for production purpose we need to set the grailsURL to "https://rundeck.nrhl.com" and port to "4443". 
Unfortunately, providing these values resulting in open ssl error as mentioned above.

**Comment by PowerSchill** [comment]
Assuming that you aren't using the Apache front end, are you setting use_inbuilt_ssl?

**Comment by gangadhar01a** [comment]
@PowerSchill I haven't defined "use_inbuilt_ssl" in my recipe and not using Apache too.

**Comment by PowerSchill** [comment]
I think use_inbuilt_ssl is needed to do ssl when not using Apache but not really sure since I do Apache. I will see if I can set up a test for it.

**Comment by gangadhar01a** [comment]
I have set use_inbuilt_ssl  to true and tried, which complained the following error

      OpenSSL::SSL::SSLError
      ----------------------
      SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol

**Comment by gangadhar01a** [comment]
Updated the NGINX confi to support TLS, which fixed the issue. 

Thanks for co-ordinating and providing the required information @PowerSchill
