### ISSUE TITLE
Any changes in chef cookBook? Some of the functionalities are not available.

### ISSUE THREAD

**Issue by gangadhar01a** [sous-chefs/rundeck#258]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

Since Nov we have started using rundeck cookbook to manage application and we haven't pinned the version of cookbook in metadata.rb (depends 'rundeck').  
Since few days we have identified the following issues
1) option to hide fields for secure options is no longer there
2) inline scripts are no longer working, due to this jobs are failing. Last time job was executed successfully was on 12/24/2019, since 1/13/2020 jobs are started failing. 

ERROR:
09:07:39 | [stub] copy local file to node rundeck: /tmp/0-1054-udc-rundeck-dispatch-script.tmp.sh
-- | --
09:07:39 | chmod: cannot access ‘/tmp/0-1054-rundeck-dispatch-script.tmp.sh’: No such file or directory
09:07:39 | Result: 1
09:07:39 | Failed: NonZeroResultCode: Result code was 1

I haven't find any scripts in tmp folder on rundeck machine.

3) It's also failing to copy the script locally (using stub plugin)
4) And the UI has definitely changed.

Rundeck version: 3.0.8-20181029

## :pancakes: Cookbook version

Haven't pinned the version, so it's using the latest (5.0.3)

## :woman_cook:  Chef-Infra Version

chef-client version 15
## :tophat: Platform details

Centos 7

**Comment by PowerSchill** [comment]
We haven't released a new version since October 2019 so it wouldn't be a new release. Has the version of Rundeck been updated in your repo? I know there have been some big changes with packages and the UI recently.

**Comment by gangadhar01a** [comment]
I haven't mentioned the rundeck version in cookbook.  I have been through the cirlceCI builds to know what version the cookbook pulled to install and I can confirm since few months it's running on Rundeck 3.0.8-20181029

CircleCI builds:
3months ago:
    * yum_package[rundeck-config] action install
      - install version 3.0.8.20181029-1.201810292220 of package rundeck-config
    * yum_package[rundeck] action install
      - install version 3.0.8.20181029-1.201810292220 of package rundeck

Most recent circleCI:
    * yum_package[rundeck-config] action install
      - install version 3.0.8.20181029-1.201810292220 of package rundeck-config
    * yum_package[rundeck] action install
      - install version 3.0.8.20181029-1.201810292220 of package rundeck

**Comment by PowerSchill** [comment]
Nothing has changed so I don't know why your builds would have just started failing if the Rundeck version is still the same.
