### ISSUE TITLE
Create LWRP: Execute

### ISSUE THREAD

**Issue by pcross616** [sous-chefs/rundeck#26]

**Comment by nkadel-skyhook** [comment]
Please do not *discard* the standard configuration of a basic rundeck server in the process of activating an LWRP. Doing so has become common practice with many shifts of existing cookbooks to an LWRP, and it's proven problematic when the working cookbook loses critical features. This happened particularly with the "mysql" and the refactoring of the "yum" cookbook.

**Comment by PowerSchill** [comment]
Closing issue. If still valid please reopen with more information.
